apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: Always #IfNotPresent, Never
    imagePullSecrets:
      - name: myregistrykey
    ports:
    - containerPort: 80
      name: http
      protocol: TCP
      hostPort: 8090
  nodeName: workerone
  nodeSelector:
    test-server-node: enabled
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    securityContext:
      privileged: true
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  containers:
  - name: nginxone
    image: nginx
    imagePullPolicy: Always #IfNotPresent, Never
    ports:
    - containerPort: 80
  - name: nginxtwo
    image: nginx
    imagePullPolicy: Always #IfNotPresent, Never
    ports:
      - containerPort: 80
    volumeMounts:
    - name: www-data
      mountPath: /usr/share/nginx/html/index.html
      subPath: index.html
  volumes:
        - name: www
          downwardAPI:
            items:
              - path: "index.html"
                fieldRef:
                  fieldPath: metadata.name
---
apiVersion: v1
kind: Pod
metadata:
  name: multi-test
spec:
  volumes:
  - name: html
    emptyDir: {}
  containers:
  - name: 1st
    image: nginx
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
  - name: 2nd
    image: debian
    volumeMounts:
    - name: html
      mountPath: /html
    command: ["/bin/sh", "-c"]
    args:
      - while true; do
          date >> /html/index.html;
          sleep 1;
        done